"""Per-repository line-count cache.

Counting lines of code means walking every commit of every repository, which is
by far the most expensive part of a build.  The result only changes when a
repository's default branch moves, so we key each entry on the head commit SHA
and re-walk only what actually changed.  (Keying on a commit *count*, as the
original does, silently misses amends, rebases, and force-pushes.)

The file is plain JSON committed alongside the repo -- readable, diffable, and
safe to delete: the next build just rebuilds it.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path

SCHEMA_VERSION = 1
DEFAULT_PATH = Path("cache/loc.json")


@dataclass
class Entry:
    head: str  # default-branch head SHA this entry was computed from
    added: int
    deleted: int
    commits: int


class LocCache:
    def __init__(self, path: Path = DEFAULT_PATH):
        self.path = Path(path)
        self.entries: dict[str, Entry] = {}
        self.hits = 0
        self.misses = 0
        self._load()

    def _load(self) -> None:
        if not self.path.exists():
            return
        try:
            raw = json.loads(self.path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            return  # corrupt cache is not an error; rebuild it
        if raw.get("schema") != SCHEMA_VERSION:
            return  # schema bump invalidates everything
        self.entries = {
            name: Entry(**data) for name, data in (raw.get("repos") or {}).items()
        }

    def get(self, repo: str, head: str) -> Entry | None:
        entry = self.entries.get(repo)
        if entry and entry.head == head:
            self.hits += 1
            return entry
        self.misses += 1
        return None

    def put(self, repo: str, entry: Entry) -> None:
        self.entries[repo] = entry

    def prune(self, live_repos: set[str]) -> None:
        """Drop repositories that no longer appear in the account."""
        for name in set(self.entries) - live_repos:
            del self.entries[name]

    def totals(self) -> tuple[int, int, int]:
        added = sum(e.added for e in self.entries.values())
        deleted = sum(e.deleted for e in self.entries.values())
        commits = sum(e.commits for e in self.entries.values())
        return added, deleted, commits

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "schema": SCHEMA_VERSION,
            "_comment": "Generated by profilecard. Safe to delete; it will be rebuilt.",
            "repos": {name: asdict(e) for name, e in sorted(self.entries.items())},
        }
        self.path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="utf-8")
