"""Per-repository line-count cache.

Counting lines of code means walking every commit of every repository, which is
by far the most expensive part of a build.  The result only changes when a
repository's default branch moves, so we key each entry on the head commit SHA
and re-walk only what actually changed.  (Keying on a commit *count*, as the
original does, silently misses amends, rebases, and force-pushes.)

The file is plain JSON committed alongside the repo, and safe to delete: the
next build just rebuilds it.

Repository names are stored **hashed**.  This file lives in a public repository,
and the accounts this is most useful for are exactly the ones whose work is
private -- publishing a list of their private repository names as a side effect
of caching would be a nasty surprise.  The cache only needs a stable key, so it
does not keep the name at all.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path

# 2: repository names are hashed rather than stored in the clear.
SCHEMA_VERSION = 2
DEFAULT_PATH = Path("cache/loc.json")


def repo_key(name_with_owner: str) -> str:
    """Stable, non-reversible key for a repository."""
    return hashlib.sha256(name_with_owner.encode("utf-8")).hexdigest()[:16]


@dataclass
class Entry:
    head: str  # default-branch head SHA this entry was computed from
    added: int
    deleted: int
    commits: int


class LocCache:
    def __init__(self, path: Path = DEFAULT_PATH):
        self.path = Path(path)
        self.entries: dict[str, Entry] = {}
        self.hits = 0
        self.misses = 0
        self._load()

    def _load(self) -> None:
        if not self.path.exists():
            return
        try:
            raw = json.loads(self.path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            return  # corrupt cache is not an error; rebuild it
        if raw.get("schema") != SCHEMA_VERSION:
            return  # schema bump invalidates everything
        self.entries = {
            name: Entry(**data) for name, data in (raw.get("repos") or {}).items()
        }

    def get(self, repo: str, head: str) -> Entry | None:
        entry = self.entries.get(repo_key(repo))
        if entry and entry.head == head:
            self.hits += 1
            return entry
        self.misses += 1
        return None

    def put(self, repo: str, entry: Entry) -> None:
        self.entries[repo_key(repo)] = entry

    def prune(self, live_repos: set[str]) -> None:
        """Drop repositories that no longer appear in the account."""
        live_keys = {repo_key(name) for name in live_repos}
        for key in set(self.entries) - live_keys:
            del self.entries[key]

    def totals(self) -> tuple[int, int, int]:
        added = sum(e.added for e in self.entries.values())
        deleted = sum(e.deleted for e in self.entries.values())
        commits = sum(e.commits for e in self.entries.values())
        return added, deleted, commits

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "schema": SCHEMA_VERSION,
            "_comment": (
                "Generated by profilecard. Safe to delete; it will be rebuilt. "
                "Keys are hashed repository names -- this file is published, and "
                "private repository names should not be."
            ),
            "repos": {name: asdict(e) for name, e in sorted(self.entries.items())},
        }
        self.path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="utf-8")
